name: "scc"
repository: github.com/hazcod/trivy-plugin-scc
version: "v0.0.1"
usage: trivy scc <srcPath>
description: A Trivy plugin that sends results to Google Cloud Security Command Center.
platforms:
  - selector: # optional
      os: linux
      arch: amd64
    uri: https://github.com/hazcod/trivy-plugin-scc/releases/download/v0.11.1/linux_amd64_v0.11.1.tar.gz
    bin: ./asccqua
  - selector:
      os: linux
      arch: arm64
    uri: https://github.com/hazcod/trivy-plugin-scc/releases/download/v0.11.1/linux_arm64_v0.11.1.tar.gz
    bin: ./scc
  - selector:
      os: darwin
      arch: arm64
    uri: https://github.com/hazcod/trivy-plugin-scc/releases/download/v0.11.1/darwin_amd64_v0.11.1.tar.gz
    bin: ./scc
  - selector:
      os: darwin
      arch: arm64
    uri: https://github.com/hazcod/trivy-plugin-scc/releases/download/v0.11.1/darwin_arm64_v0.11.1.tar.gz
    bin: ./scc
  - selector:
      os: windows
      arch: amd64
    uri: https://github.com/hazcod/trivy-plugin-scc/releases/download/v0.11.1/windows_amd64_v0.11.1.zip
    bin: scc.exe